name: Build cross platform
run-name: The ${{ github.repository }} building for a windows and linux.
on: [push]
jobs:
  Building-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: "Install Rust"
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -y | sh

      - name: "Update Rust"
        run: rustup update

      - name: "Add Linux target to rustup"
        run: rustup target add x86_64-unknown-linux-gnu

      - name: "Build"
        run: cargo build --target x86_64-unknown-linux-gnu --release
        working-directory: projects/guessing_game

  Building-Windows:
    runs-on: windows-latest
    steps:
      - name: "Install Rust"
        run: Invoke-WebRequest -Uri https://sh.rustup.rs -OutFile rustup-init.exe; Start-Process -Wait -FilePath rustup-init.exe -ArgumentList "-y"

      - name: "Update Rust"
        run: rustup update

      - name: "Add Windows target to rustup"
        run: rustup target add x86_64-pc-windows-gnu

      - name: "Build"
        run: cargo build --target x86_64-pc-windows-gnu --release
        working-directory: projects/guessing_game